package com.yanzong.controller;

import com.yanzong.service.ActivityService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;
import java.time.LocalDate;import java.util.*;

@RestController
public class PlatformController {
  private final JdbcTemplate db;private final ActivityService activity;
  public PlatformController(JdbcTemplate db,ActivityService activity){this.db=db;this.activity=activity;}
  @GetMapping("/healthz") public Map<String,Object> health(){return Map.of("status","ok","service","yanzong-governance-api","database","mysql","cache","redis");}
  @GetMapping("/api/v1/admin/activity") public Map<String,Object> activity(@RequestParam(defaultValue="12")int limit){var items=activity.latest(limit);return Map.of("items",items,"total",items.size(),"sources",sourceCounts());}
  @GetMapping("/api/v1/admin/activity/summary") public Map<String,Object> activitySummary(){return Map.of("total",db.queryForObject("select count(*) from activity_log",Long.class),"sources",sourceCounts(),"latest",activity.latest(5));}
  @GetMapping("/api/v1/cameras") public Map<String,Object> cameras(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="50")int size){List<Map<String,Object>> items=List.of(camera("CAM-037","图书馆北门",32.1262,114.0674,"online"),camera("CAM-052","教学楼A座出口",32.1281,114.0703,"online"),camera("CAM-018","学生食堂东侧",32.1247,114.0648,"online"),camera("CAM-061","体育馆西广场",32.1219,114.0712,"degraded"));return Map.of("items",items,"total",items.size(),"page",page,"size",size);}
  @GetMapping("/api/v1/events") public Map<String,Object> events(@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="50")int size){List<Map<String,Object>> items=new ArrayList<>();for(int i=0;i<6;i++)items.add(event(i));return Map.of("items",items,"total",items.size(),"page",page,"size",size);}
  @PostMapping("/api/v1/events/simulate") public Map<String,Object> simulate(){var e=event((int)(System.currentTimeMillis()%1000));String order="GD"+System.currentTimeMillis();db.update("insert into work_order(order_no,event_id,camera_id,location_name,status,priority) values(?,?,?,?,?,?)",order,e.get("event_id"),e.get("camera_id"),"体育馆西广场","pending","高");activity.record("admin","EVENT_SIMULATED","超级管理员",String.valueOf(e.get("event_id")),"模拟违规事件并自动生成工单 "+order);return Map.of("event",e,"order_no",order,"message","已生成事件和待派工单");}
  @GetMapping("/api/v1/suggestions") public Map<String,Object> suggestions(){return Map.of("items",List.of());}
  @GetMapping("/api/v1/stats/overview") public Map<String,Object> overview(){long total=db.queryForObject("select count(*) from work_order",Long.class);long done=db.queryForObject("select count(*) from work_order where status in ('closed','completed')",Long.class);long doing=db.queryForObject("select count(*) from work_order where status not in ('closed','completed')",Long.class);Map<String,Object> metrics=new LinkedHashMap<>();metrics.put("todayViolations",27);metrics.put("processingEvents",doing);metrics.put("onlineDevices",4);metrics.put("onlineStaff",6);metrics.put("todayViolationsDelta",-11.2);metrics.put("processingEventsDelta",-25);metrics.put("onlineDevicesDelta",0);metrics.put("onlineStaffDelta",0);metrics.put("workorderTotal",total);metrics.put("workorderCompleted",done);metrics.put("workorderCompletionRate",total==0?0:Math.round(done*1000.0/total)/10.0);metrics.put("avgResponseMin",9.5);metrics.put("unclosedCount",doing);return Map.of("metrics",metrics,"health",Map.of("deviceOnlineRate",75,"serviceAvailability",99.9,"storageHealth",62.4,"cameraTotal",4,"cameraOnline",3),"demo",false);}
  @GetMapping("/api/v1/stats/trend") public Map<String,Object> trend(){List<Map<String,Object>> items=new ArrayList<>();int[] d={8,10,11,13,12,13,12},h={4,5,6,8,7,8,7};for(int i=0;i<7;i++)items.add(Map.of("date",LocalDate.now().minusDays(6-i).toString(),"detected",d[i],"handled",h[i]));return Map.of("items",items);}
  private Map<String,Object> sourceCounts(){Map<String,Object> out=new LinkedHashMap<>();db.queryForList("select source,count(*) n from activity_log group by source").forEach(x->out.put(String.valueOf(x.get("source")),x.get("n")));return out;}
  private Map<String,Object> camera(String id,String name,double lat,double lng,String status){return Map.of("camera_id",id,"name",name,"location_name",name,"latitude",lat,"longitude",lng,"status",status,"fps",25,"preprocess_enabled",true,"preprocess_algorithm","retinex","online_rate",status.equals("online")?99.2:76.8);}
  private Map<String,Object> event(int i){Map<String,Object> e=new LinkedHashMap<>();e.put("id",i+1);e.put("event_id","EVT20260928"+String.format("%03d",i+1));e.put("camera_id","CAM-037");e.put("camera_name","图书馆北门");e.put("track_id",8200+i);e.put("stage","THROW_CONFIRMED");e.put("confidence",.83+(i%7)*.02);e.put("bbox",List.of(0.38,0.42,0.46,0.76));e.put("trajectory",List.of());e.put("event_timestamp","2026-09-28T18:"+String.format("%02d",i%60)+":00");e.put("status","confirmed");e.put("evidence_frames",List.of(Map.of("frame_ts","0.0","type","landed","path","/media/admin-carousel-ai.png")));e.put("video_clip_path","");e.put("has_workorder",true);return e;}
}
