-- 使用 MySQL 管理员执行，并先替换下面的 CHANGE_ME_STRONG_PASSWORD。
CREATE DATABASE IF NOT EXISTS `yanzong`
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'yanzong'@'127.0.0.1'
  IDENTIFIED BY 'CHANGE_ME_STRONG_PASSWORD';
ALTER USER 'yanzong'@'127.0.0.1'
  IDENTIFIED BY 'CHANGE_ME_STRONG_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, INDEX, REFERENCES
  ON `yanzong`.* TO 'yanzong'@'127.0.0.1';
FLUSH PRIVILEGES;
